USE ADVANCED_SQL_DB;

SELECT * FROM ORDERS;

SELECT * FROM ORDER_ITEMS;


-- DAILY PRODUCT-WISE ORDER COUNT AND SALES AMOUNT
-- ORDER DATE, PRODUCT NAME, ORDER COUNT, SALES AMOUNT

SELECT
	O.ORDER_DATE,
    P.PRODUCT_NAME,
    COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
    SUM(OI.QUANTITY) AS ORDER_QUANTITY,
    SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT)) AS SALES_VOLUME
FROM ORDERS AS O
LEFT JOIN 
	ORDER_ITEMS AS OI ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN
	PRODUCTS AS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1, 2
ORDER BY 1, 2;


-- dummy code
SELECT
	ORDER_DATE,
    MAJOR_CATEGORIES,
    COUNT(DISTINCT ORDER_ID) AS NO_OF_ORDERS,
    AVG(ORDER_VALUE) AS AVERAGE_ORDER_VALUE
FROM ORDERS
WHERE ORDER_DATE BETWEEN '2025-10-01' AND '2025-10-31'
	AND ORDER_STATUS <> 'cancelled'
    AND ORDER_DONE_DATE IS NOT NULL
    AND SALES_CHANNEL_ID IN (3,14)
GROUP BY
	ORDER_DATE, MAJOR_CATEGORIES
ORDER BY ORDER_DATE DESC;

